sudo: false

language: python

python:
- '2.7'
- '3.6'

branches:
  only:
  - master
  - fix_exception_handling

before_install:
- pwd
- pip install cython pytest pytest-mock
- pip install -r requirements.txt
- pip install ./

script:
- pytest -vvv --import-mode=append
